### ISSUE TITLE
Checklist GCMS

### ISSUE THREAD

**Issue by RaphaelAlcantara** [RaphaelAlcantara/GCMS-Raphael-Alcantara#2]
- [x] o Instalar Git localmente

- [x] o Criar projeto local

- [x] o Criar repositório local e realizar commits

- [x] o Subir alterações para o repositório remoto o Fazer alterações no repositório da turma

@ramidedantas

**Comment by ramidedantas** [comment]
OK, deixar aberto.

**Comment by RaphaelAlcantara** [comment]
Fechando Issue devido a realização da pratica 3
